# Generated by Django 5.2.6 on 2025-09-05 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={},
        ),
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.CharField(blank=True, choices=[('CS', 'Computer Science'), ('AI', 'Artificial Intelligence'), ('FIN', 'Finance'), ('MKT', 'Marketing'), ('MGMT', 'Management'), ('IT', 'Information Technology')], max_length=50),
        ),
    ]
